// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class CookIGNTest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CookIGNTest1() {
    // Test name: Cook_IGN Test 1 
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://www.ign.com/");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.manage().window().setSize(new Dimension(1552, 840));
    // 3 | click | css=.search-icon #Rectangle |  | 
    driver.findElement(By.cssSelector(".search-icon #Rectangle")).click();
    // 4 | click | css=.search-icon #Rectangle |  | 
    driver.findElement(By.cssSelector(".search-icon #Rectangle")).click();
    // 5 | click | id=search-input |  | 
    driver.findElement(By.id("search-input")).click();
    // 6 | type | id=search-input | anno 1800 | 
    driver.findElement(By.id("search-input")).sendKeys("anno 1800");
    // 7 | click | css=.search-button |  | 
    driver.findElement(By.cssSelector(".search-button")).click();
    // 8 | runScript | window.scrollTo(0,198.39999389648438) |  | 
    js.executeScript("window.scrollTo(0,198.39999389648438)");
    // 9 | runScript | window.scrollTo(0,472) |  | 
    js.executeScript("window.scrollTo(0,472)");
    // 10 | click | css=.search-item:nth-child(3) em:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".search-item:nth-child(3) em:nth-child(1)")).click();
    // 11 | runScript | window.scrollTo(0,472.79998779296875) |  | 
    js.executeScript("window.scrollTo(0,472.79998779296875)");
  }
}
